// test_inference.cpp — C++ TorchScript Inference Verification
// Online Human Intent Predictor with Adaptive Learning
//
// Verifies both TorchScript inference paths:
//
//   1. forward(x)
//        -> prediction [1, 15, 99]
//
//   2. forward_with_hidden(x)
//        -> prediction [1, 15, 99]
//        -> hidden     [1, 128]
//
// The corresponding Python references are generated by
// export_torchscript.py and stored in test_io.pt.
//
// Usage:
//   ./test_inference <intent_model.pt> <test_io.pt>

#include <chrono>
#include <fstream>
#include <iostream>
#include <vector>

#include <torch/torch.h>
#include <torch/script.h>
#include <c10/util/Exception.h>


constexpr int K = 15;
constexpr int D = 99;
constexpr int HIDDEN = 128;

constexpr double RTOL = 1e-4;
constexpr double ATOL = 1e-4;


// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
int main(int argc, char* argv[])
{
    // ------------------------------------------------------------------
    // 0. Argument check
    // ------------------------------------------------------------------
    if (argc < 3) {
        std::cerr
            << "Usage: "
            << argv[0]
            << " <intent_model.pt> <test_io.pt>\n";

        return 1;
    }


    // ------------------------------------------------------------------
    // 1. Device selection
    // ------------------------------------------------------------------
    torch::Device device(torch::kCPU);

    if (torch::cuda::is_available()) {
        device = torch::Device(torch::kCUDA);

        std::cout
            << "CUDA available - using GPU.\n";
    }
    else {
        std::cout
            << "CUDA unavailable - using CPU.\n";
    }


    // ------------------------------------------------------------------
    // 2. Load TorchScript model
    // ------------------------------------------------------------------
    torch::jit::script::Module model;

    try {
        model = torch::jit::load(argv[1]);

        model.to(device);
        model.eval();

        std::cout
            << "Model loaded.\n";
    }
    catch (const c10::Error& e) {
        std::cerr
            << "Error loading model: "
            << e.what()
            << "\n";

        return 1;
    }


    // ------------------------------------------------------------------
    // 3. Load Python-generated test_io.pt
    //
    // Expected keys:
    //
    //   x             [1, 30, 99]
    //   y             [1, 15, 99]
    //   hidden        [1, 128]
    //   y_with_hidden [1, 15, 99]
    // ------------------------------------------------------------------
    torch::Tensor x;
    torch::Tensor y;
    torch::Tensor hidden_ref;
    torch::Tensor y_with_hidden_ref;

    try {
        std::ifstream file(
            argv[2],
            std::ios::binary | std::ios::ate
        );

        if (!file.is_open()) {
            std::cerr
                << "Cannot open test_io.pt: "
                << argv[2]
                << "\n";

            return 1;
        }

        std::streamsize size =
            file.tellg();

        file.seekg(
            0,
            std::ios::beg
        );

        std::vector<char> buffer(size);

        if (!file.read(buffer.data(), size)) {
            std::cerr
                << "Failed to read test_io.pt\n";

            return 1;
        }

        c10::IValue loaded =
            torch::pickle_load(buffer);

        auto data_dict =
            loaded.toGenericDict();

        x =
            data_dict.at("x").toTensor();

        y =
            data_dict.at("y").toTensor();

        hidden_ref =
            data_dict.at("hidden").toTensor();

        y_with_hidden_ref =
            data_dict.at("y_with_hidden").toTensor();

        std::cout
            << "Test I/O loaded.\n"
            << "  x             : "
            << x.sizes()
            << "\n"
            << "  y             : "
            << y.sizes()
            << "\n"
            << "  hidden        : "
            << hidden_ref.sizes()
            << "\n"
            << "  y_with_hidden : "
            << y_with_hidden_ref.sizes()
            << "\n";
    }
    catch (const c10::Error& e) {
        std::cerr
            << "Error loading test_io.pt: "
            << e.what()
            << "\n";

        return 1;
    }


    // ------------------------------------------------------------------
    // 4. Move tensors to model device
    // ------------------------------------------------------------------
    x =
        x.to(device);

    y =
        y.to(device);

    hidden_ref =
        hidden_ref.to(device);

    y_with_hidden_ref =
        y_with_hidden_ref.to(device);

    std::cout
        << "Tensors moved to "
        << device
        << "\n";


    // ------------------------------------------------------------------
    // 5. Test ordinary forward()
    // ------------------------------------------------------------------
    torch::Tensor output;

    double normal_latency_ms = 0.0;

    try {
        torch::NoGradGuard no_grad;

        std::vector<torch::jit::IValue> inputs = {x};

        if (device.is_cuda()) {
            torch::cuda::synchronize();
        }

        auto t0 =
            std::chrono::high_resolution_clock::now();

        output =
            model.forward(inputs).toTensor();

        if (device.is_cuda()) {
            torch::cuda::synchronize();
        }

        auto t1 =
            std::chrono::high_resolution_clock::now();

        normal_latency_ms =
            std::chrono::duration<double, std::milli>(
                t1 - t0
            ).count();

        std::cout
            << "\nNormal forward complete.\n"
            << "  output shape : "
            << output.sizes()
            << "\n"
            << "  latency      : "
            << normal_latency_ms
            << " ms\n";
    }
    catch (const c10::Error& e) {
        std::cerr
            << "Error during normal inference: "
            << e.what()
            << "\n";

        return 1;
    }


    // ------------------------------------------------------------------
    // 6. Verify ordinary forward()
    // ------------------------------------------------------------------
    if (output.sizes() != y.sizes()) {
        std::cerr
            << "FAIL - normal output shape "
            << output.sizes()
            << " != Python reference "
            << y.sizes()
            << "\n";

        return 1;
    }

    auto normal_diff =
        (output - y).abs();

    float normal_max_diff =
        normal_diff.max().item<float>();

    float normal_mean_diff =
        normal_diff.mean().item<float>();

    bool normal_pass =
        torch::allclose(
            output,
            y,
            RTOL,
            ATOL
        );

    std::cout
        << std::scientific
        << "  max_diff      : "
        << normal_max_diff
        << "\n"
        << "  mean_diff     : "
        << normal_mean_diff
        << "\n"
        << std::defaultfloat;

    if (!normal_pass) {
        std::cerr
            << "FAIL - ordinary forward does not match "
            << "Python reference.\n";

        return 1;
    }

    std::cout
        << "PASS - ordinary forward matches Python.\n";


    // ------------------------------------------------------------------
    // 7. Test forward_with_hidden()
    // ------------------------------------------------------------------
    torch::Tensor prediction_with_hidden;
    torch::Tensor hidden;

    double hidden_latency_ms = 0.0;

    try {
        torch::NoGradGuard no_grad;

        std::vector<torch::jit::IValue> inputs = {x};

        auto method =
            model.get_method("forward_with_hidden");

        if (device.is_cuda()) {
            torch::cuda::synchronize();
        }

        auto t0 =
            std::chrono::high_resolution_clock::now();

        auto result =
            method(inputs);

        if (device.is_cuda()) {
            torch::cuda::synchronize();
        }

        auto t1 =
            std::chrono::high_resolution_clock::now();

        hidden_latency_ms =
            std::chrono::duration<double, std::milli>(
                t1 - t0
            ).count();

        auto tuple =
            result.toTuple();

        const auto& elements =
            tuple->elements();

        if (elements.size() != 2) {
            std::cerr
                << "FAIL - forward_with_hidden returned "
                << elements.size()
                << " values instead of 2.\n";

            return 1;
        }

        prediction_with_hidden =
            elements[0].toTensor();

        hidden =
            elements[1].toTensor();

        std::cout
            << "\nforward_with_hidden complete.\n"
            << "  prediction shape : "
            << prediction_with_hidden.sizes()
            << "\n"
            << "  hidden shape     : "
            << hidden.sizes()
            << "\n"
            << "  latency          : "
            << hidden_latency_ms
            << " ms\n";
    }
    catch (const c10::Error& e) {
        std::cerr
            << "Error during forward_with_hidden: "
            << e.what()
            << "\n";

        return 1;
    }


    // ------------------------------------------------------------------
    // 8. Shape checks
    // ------------------------------------------------------------------
    if (
        prediction_with_hidden.dim() != 3 ||
        prediction_with_hidden.size(0) != 1 ||
        prediction_with_hidden.size(1) != K ||
        prediction_with_hidden.size(2) != D
    ) {
        std::cerr
            << "FAIL - unexpected prediction shape: "
            << prediction_with_hidden.sizes()
            << "\n";

        return 1;
    }

    if (
        hidden.dim() != 2 ||
        hidden.size(0) != 1 ||
        hidden.size(1) != HIDDEN
    ) {
        std::cerr
            << "FAIL - unexpected hidden shape: "
            << hidden.sizes()
            << "\n";

        return 1;
    }


    // ------------------------------------------------------------------
    // 9. Verify forward_with_hidden prediction against Python
    // ------------------------------------------------------------------
    auto pred_hidden_diff =
        (prediction_with_hidden - y_with_hidden_ref).abs();

    float pred_hidden_max_diff =
        pred_hidden_diff.max().item<float>();

    bool pred_hidden_pass =
        torch::allclose(
            prediction_with_hidden,
            y_with_hidden_ref,
            RTOL,
            ATOL
        );

    std::cout
        << std::scientific
        << "  prediction max_diff vs Python : "
        << pred_hidden_max_diff
        << "\n"
        << std::defaultfloat;

    if (!pred_hidden_pass) {
        std::cerr
            << "FAIL - forward_with_hidden prediction "
            << "does not match Python.\n";

        return 1;
    }


    // ------------------------------------------------------------------
    // 10. Verify hidden representation against Python
    // ------------------------------------------------------------------
    auto hidden_diff =
        (hidden - hidden_ref).abs();

    float hidden_max_diff =
        hidden_diff.max().item<float>();

    float hidden_mean_diff =
        hidden_diff.mean().item<float>();

    bool hidden_pass =
        torch::allclose(
            hidden,
            hidden_ref,
            RTOL,
            ATOL
        );

    std::cout
        << std::scientific
        << "  hidden max_diff             : "
        << hidden_max_diff
        << "\n"
        << "  hidden mean_diff            : "
        << hidden_mean_diff
        << "\n"
        << std::defaultfloat;

    if (!hidden_pass) {
        std::cerr
            << "FAIL - hidden representation "
            << "does not match Python.\n";

        return 1;
    }


    // ------------------------------------------------------------------
    // 11. Verify prediction consistency between the two model methods
    // ------------------------------------------------------------------
    auto consistency_diff =
        (output - prediction_with_hidden).abs();

    float consistency_max_diff =
        consistency_diff.max().item<float>();

    bool consistency_pass =
        torch::allclose(
            output,
            prediction_with_hidden,
            RTOL,
            ATOL
        );

    std::cout
        << std::scientific
        << "  forward consistency max_diff: "
        << consistency_max_diff
        << "\n"
        << std::defaultfloat;

    if (!consistency_pass) {
        std::cerr
            << "FAIL - forward() and forward_with_hidden() "
            << "produce different predictions.\n";

        return 1;
    }


    // ------------------------------------------------------------------
    // 12. Final result
    // ------------------------------------------------------------------
    std::cout
        << "\n========================================\n"
        << "ALL TESTS PASSED\n"
        << "========================================\n"
        << "Normal forward latency      : "
        << normal_latency_ms
        << " ms\n"
        << "forward_with_hidden latency : "
        << hidden_latency_ms
        << " ms\n"
        << "Prediction shape            : "
        << prediction_with_hidden.sizes()
        << "\n"
        << "Hidden shape                : "
        << hidden.sizes()
        << "\n"
        << "========================================\n";

    return 0;
}